### ISSUE TITLE
MP_TAG does not work

### ISSUE THREAD

**Issue by LukaszRacon** [axllent/mailpit#26]
Tags don't work when defined with `MP_TAG` environment variable. Works fine with `-t` command.

Test:
`docker run --rm -it -p 1025:1025 -p 8025:8025 -e MP_TAG="abc=\"ABC\"" axllent/mailpit:v1.3.2 -v`

Looks like default value is missing:
https://github.com/axllent/mailpit/blob/master/cmd/root.go#L145:
```
- rootCmd.Flags().StringVarP(&config.SMTPCLITags, "tag", "t", "", "Tag new messages matching filters")
+ rootCmd.Flags().StringVarP(&config.SMTPCLITags, "tag", "t", "config.SMTPCLITags", "Tag new messages matching filters")
```

**Comment by axllent** [comment]
@LukaszRacon Thanks for the bug report, and you're totally right - this was missing. I have fixed this in the latest release (v1.3.3) which should finish building within the next few minutes (binaries & docker). Please let me know if this fixes it for you?

**Comment by LukaszRacon** [comment]
Thank you for quick response and developing mailpit - looks and works great. 
The issue is still there - in commit you have used wrong key: `SMTPSSLKey` instead of `SMTPCLITags`.

**Comment by axllent** [comment]
:face_with_spiral_eyes: Good catch (again!). That will teach me to try multitask! v1.3.4 with the real fix is being released now. Sorry about that... and thanks for the positive comments!

**Comment by LukaszRacon** [comment]
Confirming that all worked. Thanks again!
